package gltools.gl;


public interface GL4 extends GL3 {
	public static final int GL_UNDEFINED_VERTEX = 0x08260;
	public static final int GL_TRANSFORM_FEEDBACK_BINDING = 0x08E25;
	public static final int GL_COMPUTE_SUBROUTINE_UNIFORM = 0x092F3;
	public static final int GL_VERTEX_BINDING_STRIDE = 0x082D8;
	public static final int GL_IMAGE_1D_ARRAY = 0x09052;
	public static final int GL_INTERNALFORMAT_BLUE_SIZE = 0x08273;
	public static final int GL_IMAGE_3D = 0x0904E;
	public static final int GL_REFERENCED_BY_GEOMETRY_SHADER = 0x09309;
	public static final int GL_VERTEX_BINDING_DIVISOR = 0x082D6;
	public static final int GL_MAX_VERTEX_ATOMIC_COUNTER_BUFFERS = 0x092CC;
	public static final int GL_PIXEL_BUFFER_BARRIER_BIT = 0x00080;
	public static final int GL_PATCH_DEFAULT_INNER_LEVEL = 0x08E73;
	public static final int GL_DEBUG_TYPE_POP_GROUP = 0x0826A;
	public static final int GL_REFERENCED_BY_TESS_CONTROL_SHADER = 0x09307;
	public static final int GL_VIEW_CLASS_8_BITS = 0x082CB;
	public static final int GL_TESS_EVALUATION_SHADER_BIT = 0x00010;
	public static final int GL_DEBUG_SOURCE_OTHER = 0x0824B;
	public static final int GL_MAX_GEOMETRY_IMAGE_UNIFORMS = 0x090CD;
	public static final int GL_MAP_PERSISTENT_BIT = 0x00040;
	public static final int GL_IMAGE_2D_MULTISAMPLE_ARRAY = 0x09056;
	public static final int GL_MAX_IMAGE_UNITS = 0x08F38;
	public static final int GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 0x090DA;
	public static final int GL_ATOMIC_COUNTER_BARRIER_BIT = 0x01000;
	public static final int GL_SHADER_COMPILER = 0x08DFA;
	public static final int GL_TRANSFORM_FEEDBACK_BUFFER_INDEX = 0x0934B;
	public static final int GL_TOP_LEVEL_ARRAY_SIZE = 0x0930C;
	public static final int GL_FRAMEBUFFER_BARRIER_BIT = 0x00400;
	public static final int GL_NUM_SHADER_BINARY_FORMATS = 0x08DF9;
	public static final int GL_ISOLINES = 0x08E7A;
	public static final int GL_MAX_COMBINED_ATOMIC_COUNTERS = 0x092D7;
	public static final int GL_MAX_DEBUG_LOGGED_MESSAGES = 0x09144;
	public static final int GL_DEBUG_SEVERITY_MEDIUM = 0x09147;
	public static final int GL_INTERNALFORMAT_STENCIL_TYPE = 0x0827D;
	public static final int GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x092C9;
	public static final int GL_MAX_FRAGMENT_UNIFORM_VECTORS = 0x08DFD;
	public static final int GL_VIEWPORT_INDEX_PROVOKING_VERTEX = 0x0825F;
	public static final int GL_TESS_CONTROL_SUBROUTINE = 0x092E9;
	public static final int GL_COMPUTE_SHADER = 0x091B9;
	public static final int GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER = 0x090EC;
	public static final int GL_VIEW_CLASS_S3TC_DXT1_RGBA = 0x082CD;
	public static final int GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS = 0x0886D;
	public static final int GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY = 0x0906C;
	public static final int GL_MAX_WIDTH = 0x0827E;
	public static final int GL_IMAGE_BINDING_ACCESS = 0x08F3E;
	public static final int GL_BUFFER_DATA_SIZE = 0x09303;
	public static final int GL_NUM_COMPATIBLE_SUBROUTINES = 0x08E4A;
	public static final int GL_MAX_COMBINED_DIMENSIONS = 0x08282;
	public static final int GL_MAX_DEBUG_MESSAGE_LENGTH = 0x09143;
	public static final int GL_TESS_CONTROL_SHADER_BIT = 0x00008;
	public static final int GL_DYNAMIC_STORAGE_BIT = 0x00100;
	public static final int GL_SHADER_STORAGE_BUFFER_BINDING = 0x090D3;
	public static final int GL_MAX_COMBINED_IMAGE_UNIFORMS = 0x090CF;
	public static final int GL_DEBUG_SEVERITY_HIGH = 0x09146;
	public static final int GL_CLIP_ORIGIN = 0x0935C;
	public static final int GL_PACK_COMPRESSED_BLOCK_SIZE = 0x0912E;
	public static final int GL_INT_IMAGE_BUFFER = 0x0905C;
	public static final int GL_FRAMEBUFFER_RENDERABLE_LAYERED = 0x0828A;
	public static final int GL_TEXTURE_TARGET = 0x01006;
	public static final int GL_BUFFER = 0x082E0;
	public static final int GL_IMAGE_BINDING_LAYER = 0x08F3D;
	public static final int GL_NUM_ACTIVE_VARIABLES = 0x09304;
	public static final int GL_DOUBLE_MAT2x4 = 0x08F4A;
	public static final int GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES = 0x092C6;
	public static final int GL_VIEW_CLASS_24_BITS = 0x082C9;
	public static final int GL_COMPRESSED_RGBA8_ETC2_EAC = 0x09278;
	public static final int GL_ACTIVE_SUBROUTINE_MAX_LENGTH = 0x08E48;
	public static final int GL_DOUBLE_MAT2x3 = 0x08F49;
	public static final int GL_UNIFORM_BARRIER_BIT = 0x00004;
	public static final int GL_TESS_GEN_MODE = 0x08E76;
	public static final int GL_VIEW_CLASS_BPTC_FLOAT = 0x082D3;
	public static final int GL_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS = 0x08F39;
	public static final int GL_FRAMEBUFFER_DEFAULT_HEIGHT = 0x09311;
	public static final int GL_MEDIUM_FLOAT = 0x08DF1;
	public static final int GL_SHADER = 0x082E1;
	public static final int GL_PROGRAM = 0x082E2;
	public static final int GL_CLIP_DEPTH_MODE = 0x0935D;
	public static final int GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS = 0x08E1E;
	public static final int GL_BUFFER_UPDATE_BARRIER_BIT = 0x00200;
	public static final int GL_SHADER_STORAGE_BUFFER = 0x090D2;
	public static final int GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS = 0x08E83;
	public static final int GL_MAX_TESS_EVALUATION_IMAGE_UNIFORMS = 0x090CC;
	public static final int GL_MAX_VERTEX_ATOMIC_COUNTERS = 0x092D2;
	public static final int GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER = 0x092C8;
	public static final int GL_INTERNALFORMAT_GREEN_SIZE = 0x08272;
	public static final int GL_COMPRESSED_R11_EAC = 0x09270;
	public static final int GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER = 0x090ED;
	public static final int GL_CLIENT_STORAGE_BIT = 0x00200;
	public static final int GL_DOUBLE_MAT3x4 = 0x08F4C;
	public static final int GL_DOUBLE_MAT3x2 = 0x08F4B;
	public static final int GL_TYPE = 0x092FA;
	public static final int GL_COMPUTE_SHADER_BIT = 0x00020;
	public static final int GL_PROGRAM_BINARY_FORMATS = 0x087FF;
	public static final int GL_PROXY_TEXTURE_CUBE_MAP_ARRAY = 0x0900B;
	public static final int GL_MAX_FRAGMENT_IMAGE_UNIFORMS = 0x090CE;
	public static final int GL_IMAGE_CUBE_MAP_ARRAY = 0x09054;
	public static final int GL_NAME_LENGTH = 0x092F9;
	public static final int GL_MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS = 0x092CF;
	public static final int GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x09276;
	public static final int GL_MAX_VERTEX_ATTRIB_STRIDE = 0x082E5;
	public static final int GL_IMAGE_CUBE = 0x09050;
	public static final int GL_TEXTURE_VIEW_MIN_LEVEL = 0x082DB;
	public static final int GL_TEXTURE_COMPRESSED_BLOCK_SIZE = 0x082B3;
	public static final int GL_AUTO_GENERATE_MIPMAP = 0x08295;
	public static final int GL_MAX_TESS_CONTROL_INPUT_COMPONENTS = 0x0886C;
	public static final int GL_SAMPLER_CUBE_MAP_ARRAY = 0x0900C;
	public static final int GL_QUERY_TARGET = 0x082EA;
	public static final int GL_TRANSFORM_FEEDBACK = 0x08E22;
	public static final int GL_ALL_BARRIER_BITS = 0xFFFFFF;
	public static final int GL_TEXTURE_FETCH_BARRIER_BIT = 0x00008;
	public static final int GL_MIRROR_CLAMP_TO_EDGE = 0x08743;
	public static final int GL_VIEW_CLASS_S3TC_DXT1_RGB = 0x082CC;
	public static final int GL_INTERNALFORMAT_STENCIL_SIZE = 0x08276;
	public static final int GL_CLEAR_TEXTURE = 0x09365;
	public static final int GL_DOUBLE_MAT4x2 = 0x08F4D;
	public static final int GL_VIEW_CLASS_16_BITS = 0x082CA;
	public static final int GL_DOUBLE_MAT4x3 = 0x08F4E;
	public static final int GL_FRACTIONAL_ODD = 0x08E7B;
	public static final int GL_MEDIUM_INT = 0x08DF4;
	public static final int GL_INTERNALFORMAT_RED_SIZE = 0x08271;
	public static final int GL_ACTIVE_SUBROUTINE_UNIFORMS = 0x08DE6;
	public static final int GL_DEBUG_CALLBACK_USER_PARAM = 0x08245;
	public static final int GL_TEXTURE_GATHER = 0x082A2;
	public static final int GL_UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX = 0x092DA;
	public static final int GL_INT_IMAGE_2D_RECT = 0x0905A;
	public static final int GL_MAX_HEIGHT = 0x0827F;
	public static final int GL_DEBUG_SOURCE_SHADER_COMPILER = 0x08248;
	public static final int GL_FRAMEBUFFER_DEFAULT_LAYERS = 0x09312;
	public static final int GL_GEOMETRY_SUBROUTINE_UNIFORM = 0x092F1;
	public static final int GL_IMAGE_2D_ARRAY = 0x09053;
	public static final int GL_IMAGE_CLASS_10_10_10_2 = 0x082C3;
	public static final int GL_PACK_COMPRESSED_BLOCK_DEPTH = 0x0912D;
	public static final int GL_PACK_COMPRESSED_BLOCK_HEIGHT = 0x0912C;
	public static final int GL_TESS_GEN_POINT_MODE = 0x08E79;
	public static final int GL_LOSE_CONTEXT_ON_RESET = 0x08252;
	public static final int GL_IMAGE_BINDING_FORMAT = 0x0906E;
	public static final int GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 0x090DB;
	public static final int GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER = 0x092CB;
	public static final int GL_DEBUG_TYPE_PERFORMANCE = 0x08250;
	public static final int GL_MAX_COMPUTE_IMAGE_UNIFORMS = 0x091BD;
	public static final int GL_TESS_GEN_VERTEX_ORDER = 0x08E78;
	public static final int GL_INT_SAMPLER_CUBE_MAP_ARRAY = 0x0900E;
	public static final int GL_LAYER_PROVOKING_VERTEX = 0x0825E;
	public static final int GL_TEXTURE_BINDING = 0x082EB;
	public static final int GL_HIGH_INT = 0x08DF5;
	public static final int GL_IMAGE_FORMAT_COMPATIBILITY_BY_CLASS = 0x090C9;
	public static final int GL_INT_IMAGE_2D_ARRAY = 0x0905E;
	public static final int GL_MAX_TRANSFORM_FEEDBACK_BUFFERS = 0x08E70;
	public static final int GL_TESS_EVALUATION_TEXTURE = 0x0829D;
	public static final int GL_VERTEX_SHADER_BIT = 0x00001;
	public static final int GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS = 0x092D3;
	public static final int GL_INT_IMAGE_2D_MULTISAMPLE_ARRAY = 0x09061;
	public static final int GL_PACK_COMPRESSED_BLOCK_WIDTH = 0x0912B;
	public static final int GL_MAX_FRAMEBUFFER_HEIGHT = 0x09316;
	public static final int GL_COMMAND_BARRIER_BIT = 0x00040;
	public static final int GL_TEXTURE_BINDING_CUBE_MAP_ARRAY = 0x0900A;
	public static final int GL_SHADER_IMAGE_LOAD = 0x082A4;
	public static final int GL_COPY_READ_BUFFER_BINDING = 0x08F36;
	public static final int GL_DEBUG_SEVERITY_NOTIFICATION = 0x0826B;
	public static final int GL_ELEMENT_ARRAY_BARRIER_BIT = 0x00002;
	public static final int GL_FRAMEBUFFER_BLEND = 0x0828B;
	public static final int GL_VIEW_CLASS_96_BITS = 0x082C5;
	public static final int GL_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY = 0x0906A;
	public static final int GL_MAX_COMBINED_ATOMIC_COUNTER_BUFFERS = 0x092D1;
	public static final int GL_TEXTURE_IMMUTABLE_FORMAT = 0x0912F;
	public static final int GL_PROGRAM_BINARY_LENGTH = 0x08741;
	public static final int GL_TEXTURE_SHADOW = 0x082A1;
	public static final int GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT = 0x090DF;
	public static final int GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER = 0x092C7;
	public static final int GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY = 0x0900F;
	public static final int GL_UNSIGNED_INT_IMAGE_2D_RECT = 0x09065;
	public static final int GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER = 0x084F0;
	public static final int GL_IMAGE_PIXEL_FORMAT = 0x082A9;
	public static final int GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS = 0x090DD;
	public static final int GL_SHADER_IMAGE_ACCESS_BARRIER_BIT = 0x00020;
	public static final int GL_UNSIGNED_INT_ATOMIC_COUNTER = 0x092DB;
	public static final int GL_QUERY_BUFFER_BARRIER_BIT = 0x08000;
	public static final int GL_MAX_GEOMETRY_SHADER_INVOCATIONS = 0x08E5A;
	public static final int GL_FRAGMENT_SUBROUTINE_UNIFORM = 0x092F2;
	public static final int GL_UNSIGNED_INT_IMAGE_2D_ARRAY = 0x09069;
	public static final int GL_DEBUG_TYPE_OTHER = 0x08251;
	public static final int GL_DOUBLE_VEC4 = 0x08FFE;
	public static final int GL_DOUBLE_VEC3 = 0x08FFD;
	public static final int GL_DOUBLE_VEC2 = 0x08FFC;
	public static final int GL_LOCATION_INDEX = 0x0930F;
	public static final int GL_VERTEX_ATTRIB_ARRAY_BARRIER_BIT = 0x00001;
	public static final int GL_MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS = 0x092CD;
	public static final int GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS = 0x08266;
	public static final int GL_TEXTURE_COMPRESSED_BLOCK_HEIGHT = 0x082B2;
	public static final int GL_COMPRESSED_RGBA_BPTC_UNORM = 0x08E8C;
	public static final int GL_MATRIX_STRIDE = 0x092FF;
	public static final int GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES = 0x08F39;
	public static final int GL_QUERY_BUFFER = 0x09192;
	public static final int GL_IMAGE_PIXEL_TYPE = 0x082AA;
	public static final int GL_PATCH_DEFAULT_OUTER_LEVEL = 0x08E74;
	public static final int GL_ATOMIC_COUNTER_BUFFER_DATA_SIZE = 0x092C4;
	public static final int GL_ACTIVE_VARIABLES = 0x09305;
	public static final int GL_ACTIVE_RESOURCES = 0x092F5;
	public static final int GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x09277;
	public static final int GL_GEOMETRY_SHADER_INVOCATIONS = 0x0887F;
	public static final int GL_COMPRESSED_SRGB_ALPHA_BPTC_UNORM = 0x08E8D;
	public static final int GL_DEPTH_RENDERABLE = 0x08287;
	public static final int GL_MAX_COMPUTE_UNIFORM_COMPONENTS = 0x08263;
	public static final int GL_TRANSFORM_FEEDBACK_BARRIER_BIT = 0x00800;
	public static final int GL_PATCHES = 0x0000E;
	public static final int GL_FRAGMENT_SHADER_BIT = 0x00002;
	public static final int GL_MAX_CULL_DISTANCES = 0x082F9;
	public static final int GL_TEXTURE_GATHER_SHADOW = 0x082A3;
	public static final int GL_DEBUG_OUTPUT_SYNCHRONOUS = 0x08242;
	public static final int GL_TRANSFORM_FEEDBACK_VARYING = 0x092F4;
	public static final int GL_DOUBLE_MAT4 = 0x08F48;
	public static final int GL_ACTIVE_SUBROUTINES = 0x08DE5;
	public static final int GL_VERTEX_BINDING_OFFSET = 0x082D7;
	public static final int GL_RGB565 = 0x08D62;
	public static final int GL_DOUBLE_MAT3 = 0x08F47;
	public static final int GL_DOUBLE_MAT2 = 0x08F46;
	public static final int GL_SAMPLER = 0x082E6;
	public static final int GL_REFERENCED_BY_VERTEX_SHADER = 0x09306;
	public static final int GL_UNPACK_COMPRESSED_BLOCK_WIDTH = 0x09127;
	public static final int GL_INT_IMAGE_CUBE_MAP_ARRAY = 0x0905F;
	public static final int GL_MAX_GEOMETRY_ATOMIC_COUNTERS = 0x092D5;
	public static final int GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR = 0x0824E;
	public static final int GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS = 0x090D6;
	public static final int GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS = 0x090D8;
	public static final int GL_SRGB_DECODE_ARB = 0x08299;
	public static final int GL_VIEW_CLASS_48_BITS = 0x082C7;
	public static final int GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS = 0x090EB;
	public static final int GL_IMAGE_BINDING_LAYERED = 0x08F3C;
	public static final int GL_VIEW_CLASS_RGTC1_RED = 0x082D0;
	public static final int GL_INTERNALFORMAT_BLUE_TYPE = 0x0827A;
	public static final int GL_SRGB_WRITE = 0x08298;
	public static final int GL_INTERNALFORMAT_GREEN_TYPE = 0x08279;
	public static final int GL_VIEW_CLASS_RGTC2_RG = 0x082D1;
	public static final int GL_MAX_FRAMEBUFFER_WIDTH = 0x09315;
	public static final int GL_MAX_ELEMENT_INDEX = 0x08D6B;
	public static final int GL_TESS_GEN_SPACING = 0x08E77;
	public static final int GL_CAVEAT_SUPPORT = 0x082B8;
	public static final int GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER = 0x092CA;
	public static final int GL_MIPMAP = 0x08293;
	public static final int GL_IMAGE_COMPATIBILITY_CLASS = 0x082A8;
	public static final int GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x08E80;
	public static final int GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_WRITE = 0x082AF;
	public static final int GL_UNPACK_COMPRESSED_BLOCK_DEPTH = 0x09129;
	public static final int GL_DEPTH_STENCIL_TEXTURE_MODE = 0x090EA;
	public static final int GL_NUM_SHADING_LANGUAGE_VERSIONS = 0x082E9;
	public static final int GL_MANUAL_GENERATE_MIPMAP = 0x08294;
	public static final int GL_QUERY_NO_WAIT_INVERTED = 0x08E18;
	public static final int GL_TEXTURE_CUBE_MAP_ARRAY = 0x09009;
	public static final int GL_VIEW_CLASS_BPTC_UNORM = 0x082D2;
	public static final int GL_LOW_FLOAT = 0x08DF0;
	public static final int GL_MIN_FRAGMENT_INTERPOLATION_OFFSET = 0x08E5B;
	public static final int GL_FRAGMENT_TEXTURE = 0x0829F;
	public static final int GL_DEBUG_SOURCE_WINDOW_SYSTEM = 0x08247;
	public static final int GL_SHADER_IMAGE_ATOMIC = 0x082A6;
	public static final int GL_MAX_FRAGMENT_INTERPOLATION_OFFSET = 0x08E5C;
	public static final int GL_VIEW_CLASS_S3TC_DXT3_RGBA = 0x082CE;
	public static final int GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS = 0x08E86;
	public static final int GL_MAX_TESS_CONTROL_IMAGE_UNIFORMS = 0x090CB;
	public static final int GL_TEXTURE_VIEW = 0x082B5;
	public static final int GL_MAX_COMPUTE_WORK_GROUP_COUNT = 0x091BE;
	public static final int GL_FRACTIONAL_EVEN = 0x08E7C;
	public static final int GL_BUFFER_VARIABLE = 0x092E5;
	public static final int GL_MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS = 0x092D0;
	public static final int GL_STENCIL_COMPONENTS = 0x08285;
	public static final int GL_COLOR_RENDERABLE = 0x08286;
	public static final int GL_VIEW_CLASS_64_BITS = 0x082C6;
	public static final int GL_TESS_EVALUATION_SUBROUTINE_UNIFORM = 0x092F0;
	public static final int GL_PROGRAM_PIPELINE_BINDING = 0x0825A;
	public static final int GL_UNSIGNED_INT_IMAGE_1D_ARRAY = 0x09068;
	public static final int GL_TEXTURE_BUFFER_SIZE = 0x0919E;
	public static final int GL_IMAGE_BUFFER = 0x09051;
	public static final int GL_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x09308;
	public static final int GL_CONTEXT_LOST = 0x00507;
	public static final int GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS = 0x08E7F;
	public static final int GL_IMAGE_CLASS_4_X_8 = 0x082BF;
	public static final int GL_VERTEX_SUBROUTINE_UNIFORM = 0x092EE;
	public static final int GL_MAX_VERTEX_UNIFORM_VECTORS = 0x08DFB;
	public static final int GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS = 0x092D4;
	public static final int GL_SHADER_IMAGE_STORE = 0x082A5;
	public static final int GL_UNKNOWN_CONTEXT_RESET = 0x08255;
	public static final int GL_MAX_DEPTH = 0x08280;
	public static final int GL_TOP_LEVEL_ARRAY_STRIDE = 0x0930D;
	public static final int GL_TEXTURE_UPDATE_BARRIER_BIT = 0x00100;
	public static final int GL_DEBUG_SEVERITY_LOW = 0x09148;
	public static final int GL_COMPRESSED_SIGNED_R11_EAC = 0x09271;
	public static final int GL_QUERY = 0x082E3;
	public static final int GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_TEST = 0x082AC;
	public static final int GL_SHADER_STORAGE_BUFFER_SIZE = 0x090D5;
	public static final int GL_MIN_MAP_BUFFER_ALIGNMENT = 0x090BC;
	public static final int GL_QUERY_BY_REGION_NO_WAIT_INVERTED = 0x08E1A;
	public static final int GL_MAX_COMPUTE_WORK_GROUP_SIZE = 0x091BF;
	public static final int GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH = 0x08E49;
	public static final int GL_ATOMIC_COUNTER_BUFFER = 0x092C0;
	public static final int GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS = 0x091BC;
	public static final int GL_COLOR_ENCODING = 0x08296;
	public static final int GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS = 0x08E8A;
	public static final int GL_COMPRESSED_RGB_BPTC_UNSIGNED_FLOAT = 0x08E8F;
	public static final int GL_COMPRESSED_RG11_EAC = 0x09272;
	public static final int GL_SAMPLE_SHADING = 0x08C36;
	public static final int GL_RESET_NOTIFICATION_STRATEGY = 0x08256;
	public static final int GL_IMAGE_BINDING_NAME = 0x08F3A;
	public static final int GL_SHADER_BINARY_FORMATS = 0x08DF8;
	public static final int GL_TRANSFORM_FEEDBACK_PAUSED = 0x08E23;
	public static final int GL_TRANSFORM_FEEDBACK_BUFFER_STRIDE = 0x0934C;
	public static final int GL_INT_IMAGE_2D_MULTISAMPLE = 0x09060;
	public static final int GL_CLEAR_BUFFER = 0x082B4;
	public static final int GL_INTERNALFORMAT_DEPTH_SIZE = 0x08275;
	public static final int GL_INT_IMAGE_1D_ARRAY = 0x0905D;
	public static final int GL_MAX_FRAMEBUFFER_LAYERS = 0x09317;
	public static final int GL_DEBUG_SOURCE_APPLICATION = 0x0824A;
	public static final int GL_TEXTURE_COMPRESSED_BLOCK_WIDTH = 0x082B1;
	public static final int GL_TEXTURE_VIEW_NUM_LEVELS = 0x082DC;
	public static final int GL_PROGRAM_INPUT = 0x092E3;
	public static final int GL_IS_PER_PATCH = 0x092E7;
	public static final int GL_UNPACK_COMPRESSED_BLOCK_SIZE = 0x0912A;
	public static final int GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW = 0x0900D;
	public static final int GL_IMAGE_CLASS_1_X_32 = 0x082BB;
	public static final int GL_TRANSFORM_FEEDBACK_ACTIVE = 0x08E24;
	public static final int GL_SHADER_STORAGE_BLOCK = 0x092E6;
	public static final int GL_BUFFER_IMMUTABLE_STORAGE = 0x0821F;
	public static final int GL_MAX_VERTEX_ATTRIB_BINDINGS = 0x082DA;
	public static final int GL_MAX_FRAMEBUFFER_SAMPLES = 0x09318;
	public static final int GL_DEPTH_COMPONENTS = 0x08284;
	public static final int GL_MAX_NUM_ACTIVE_VARIABLES = 0x092F7;
	public static final int GL_TEXTURE_BUFFER_OFFSET = 0x0919D;
	public static final int GL_HIGH_FLOAT = 0x08DF2;
	public static final int GL_PROGRAM_BINARY_RETRIEVABLE_HINT = 0x08257;
	public static final int GL_REFERENCED_BY_COMPUTE_SHADER = 0x0930B;
	public static final int GL_TEXTURE_IMAGE_TYPE = 0x08290;
	public static final int GL_FIXED = 0x0140C;
	public static final int GL_VIEWPORT_SUBPIXEL_BITS = 0x0825C;
	public static final int GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_WRITE = 0x082AE;
	public static final int GL_CONTEXT_RELEASE_BEHAVIOR = 0x082FB;
	public static final int GL_DEBUG_TYPE_PORTABILITY = 0x0824F;
	public static final int GL_DISPATCH_INDIRECT_BUFFER = 0x090EE;
	public static final int GL_FRAMEBUFFER_RENDERABLE = 0x08289;
	public static final int GL_QUERY_BUFFER_BINDING = 0x09193;
	public static final int GL_ATOMIC_COUNTER_BUFFER_START = 0x092C2;
	public static final int GL_COMPRESSED_SRGB8_ETC2 = 0x09275;
	public static final int GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x08E1F;
	public static final int GL_MAX_NAME_LENGTH = 0x092F6;
	public static final int GL_SHADER_STORAGE_BUFFER_START = 0x090D4;
	public static final int GL_IMAGE_FORMAT_COMPATIBILITY_TYPE = 0x090C7;
	public static final int GL_TEXTURE_VIEW_MIN_LAYER = 0x082DD;
	public static final int GL_IMAGE_BINDING_LEVEL = 0x08F3B;
	public static final int GL_MAX_LABEL_LENGTH = 0x082E8;
	public static final int GL_MAX_TESS_GEN_LEVEL = 0x08E7E;
	public static final int GL_IMAGE_CLASS_1_X_16 = 0x082BE;
	public static final int GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x082D9;
	public static final int GL_INTERNALFORMAT_PREFERRED = 0x08270;
	public static final int GL_UNIFORM = 0x092E1;
	public static final int GL_FILTER = 0x0829A;
	public static final int GL_MAX_COMPUTE_ATOMIC_COUNTERS = 0x08265;
	public static final int GL_INTERNALFORMAT_ALPHA_SIZE = 0x08274;
	public static final int GL_ATOMIC_COUNTER_BUFFER_INDEX = 0x09301;
	public static final int GL_MAX_VERTEX_IMAGE_UNIFORMS = 0x090CA;
	public static final int GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR = 0x0824D;
	public static final int GL_FULL_SUPPORT = 0x082B7;
	public static final int GL_FRAGMENT_INTERPOLATION_OFFSET_BITS = 0x08E5D;
	public static final int GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET = 0x08E5E;
	public static final int GL_GEOMETRY_SHADER_BIT = 0x00004;
	public static final int GL_IMAGE_CLASS_2_X_8 = 0x082C0;
	public static final int GL_TEXTURE_VIEW_NUM_LAYERS = 0x082DE;
	public static final int GL_IMPLEMENTATION_COLOR_READ_TYPE = 0x08B9A;
	public static final int GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH = 0x08243;
	public static final int GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS = 0x090DC;
	public static final int GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS = 0x08E81;
	public static final int GL_DEBUG_OUTPUT = 0x092E0;
	public static final int GL_MAX_COMPUTE_UNIFORM_BLOCKS = 0x091BB;
	public static final int GL_PROGRAM_SEPARABLE = 0x08258;
	public static final int GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT = 0x04000;
	public static final int GL_DEBUG_LOGGED_MESSAGES = 0x09145;
	public static final int GL_NEGATIVE_ONE_TO_ONE = 0x0935E;
	public static final int GL_IMAGE_TEXEL_SIZE = 0x082A7;
	public static final int GL_MIN_SAMPLE_SHADING_VALUE = 0x08C37;
	public static final int GL_ACTIVE_ATOMIC_COUNTER_BUFFERS = 0x092D9;
	public static final int GL_MAX_UNIFORM_LOCATIONS = 0x0826E;
	public static final int GL_MAX_TESS_PATCH_COMPONENTS = 0x08E84;
	public static final int GL_VERTEX_ATTRIB_BINDING = 0x082D4;
	public static final int GL_GEOMETRY_SUBROUTINE = 0x092EB;
	public static final int GL_MAX_VARYING_VECTORS = 0x08DFC;
	public static final int GL_READ_PIXELS_TYPE = 0x0828E;
	public static final int GL_IMAGE_CLASS_4_X_16 = 0x082BC;
	public static final int GL_MAX_SUBROUTINES = 0x08DE7;
	public static final int GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = 0x09279;
	public static final int GL_VERTEX_ATTRIB_ARRAY_LONG = 0x0874E;
	public static final int GL_STENCIL_RENDERABLE = 0x08288;
	public static final int GL_CONTEXT_ROBUST_ACCESS = 0x090F3;
	public static final int GL_MAX_ATOMIC_COUNTER_BUFFER_BINDINGS = 0x092DC;
	public static final int GL_ARRAY_STRIDE = 0x092FE;
	public static final int GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT = 0x0919F;
	public static final int GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS = 0x08E82;
	public static final int GL_INT_IMAGE_CUBE = 0x0905B;
	public static final int GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED = 0x08E23;
	public static final int GL_PROGRAM_PIPELINE = 0x082E4;
	public static final int GL_TEXTURE_IMMUTABLE_LEVELS = 0x082DF;
	public static final int GL_UNIFORM_BLOCK = 0x092E2;
	public static final int GL_VIEW_CLASS_128_BITS = 0x082C4;
	public static final int GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS = 0x08264;
	public static final int GL_NO_RESET_NOTIFICATION = 0x08261;
	public static final int GL_DEBUG_CALLBACK_FUNCTION = 0x08244;
	public static final int GL_OFFSET = 0x092FC;
	public static final int GL_VIEW_COMPATIBILITY_CLASS = 0x082B6;
	public static final int GL_COMPUTE_WORK_GROUP_SIZE = 0x08267;
	public static final int GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS = 0x08E47;
	public static final int GL_DEBUG_TYPE_PUSH_GROUP = 0x08269;
	public static final int GL_FRAGMENT_SUBROUTINE = 0x092EC;
	public static final int GL_IMAGE_CLASS_2_X_16 = 0x082BD;
	public static final int GL_UNSIGNED_INT_IMAGE_BUFFER = 0x09067;
	public static final int GL_INTERNALFORMAT_SUPPORTED = 0x0826F;
	public static final int GL_UNPACK_COMPRESSED_BLOCK_HEIGHT = 0x09128;
	public static final int GL_MAX_COMPUTE_SHARED_MEMORY_SIZE = 0x08262;
	public static final int GL_PATCH_VERTICES = 0x08E72;
	public static final int GL_NUM_SAMPLE_COUNTS = 0x09380;
	public static final int GL_COPY_WRITE_BUFFER_BINDING = 0x08F37;
	public static final int GL_MAX_COMBINED_CLIP_AND_CULL_DISTANCES = 0x082FA;
	public static final int GL_TEXTURE_IMAGE_FORMAT = 0x0828F;
	public static final int GL_ACTIVE_PROGRAM = 0x08259;
	public static final int GL_VERTEX_TEXTURE = 0x0829B;
	public static final int GL_BUFFER_BINDING = 0x09302;
	public static final int GL_DEBUG_TYPE_MARKER = 0x08268;
	public static final int GL_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE = 0x0906B;
	public static final int GL_DISPLAY_LIST = 0x082E7;
	public static final int GL_UNSIGNED_INT_IMAGE_2D = 0x09063;
	public static final int GL_CONTEXT_FLAG_DEBUG_BIT = 0x00002;
	public static final int GL_BUFFER_STORAGE_FLAGS = 0x08220;
	public static final int GL_MAX_PATCH_VERTICES = 0x08E7D;
	public static final int GL_FRAMEBUFFER_DEFAULT_SAMPLES = 0x09313;
	public static final int GL_QUERY_RESULT_NO_WAIT = 0x09194;
	public static final int GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS = 0x08E89;
	public static final int GL_GET_TEXTURE_IMAGE_FORMAT = 0x08291;
	public static final int GL_COMPRESSED_RGB8_ETC2 = 0x09274;
	public static final int GL_TESS_CONTROL_SUBROUTINE_UNIFORM = 0x092EF;
	public static final int GL_INNOCENT_CONTEXT_RESET = 0x08254;
	public static final int GL_DRAW_INDIRECT_BUFFER_BINDING = 0x08F43;
	public static final int GL_ATOMIC_COUNTER_BUFFER_SIZE = 0x092C3;
	public static final int GL_COMPUTE_SUBROUTINE = 0x092ED;
	public static final int GL_VIEWPORT_BOUNDS_RANGE = 0x0825D;
	public static final int GL_IMAGE_2D_RECT = 0x0904F;
	public static final int GL_COMPUTE_TEXTURE = 0x082A0;
	public static final int GL_LOCATION = 0x0930E;
	public static final int GL_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x082D5;
	public static final int GL_NUM_PROGRAM_BINARY_FORMATS = 0x087FE;
	public static final int GL_PRIMITIVE_RESTART_FIXED_INDEX = 0x08D69;
	public static final int GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 0x08D6A;
	public static final int GL_UNSIGNED_INT_IMAGE_1D = 0x09062;
	public static final int GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_TEST = 0x082AD;
	public static final int GL_IS_ROW_MAJOR = 0x09300;
	public static final int GL_VERTEX_SUBROUTINE = 0x092E8;
	public static final int GL_MAX_ATOMIC_COUNTER_BUFFER_SIZE = 0x092D8;
	public static final int GL_INTERNALFORMAT_SHARED_SIZE = 0x08277;
	public static final int GL_GEOMETRY_TEXTURE = 0x0829E;
	public static final int GL_COLOR_COMPONENTS = 0x08283;
	public static final int GL_COMPATIBLE_SUBROUTINES = 0x08E4B;
	public static final int GL_DRAW_INDIRECT_BUFFER = 0x08F3F;
	public static final int GL_DEBUG_SOURCE_API = 0x08246;
	public static final int GL_IMAGE_CLASS_1_X_8 = 0x082C1;
	public static final int GL_IMAGE_CLASS_2_X_32 = 0x082BA;
	public static final int GL_MAX_DEBUG_GROUP_STACK_DEPTH = 0x0826C;
	public static final int GL_GET_TEXTURE_IMAGE_TYPE = 0x08292;
	public static final int GL_MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS = 0x08F9F;
	public static final int GL_MAX_FRAGMENT_ATOMIC_COUNTERS = 0x092D6;
	public static final int GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x084F1;
	public static final int GL_TESS_CONTROL_OUTPUT_VERTICES = 0x08E75;
	public static final int GL_INTERNALFORMAT_RED_TYPE = 0x08278;
	public static final int GL_INTERNALFORMAT_ALPHA_TYPE = 0x0827B;
	public static final int GL_TESS_CONTROL_TEXTURE = 0x0829C;
	public static final int GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS = 0x090D7;
	public static final int GL_MAX_LAYERS = 0x08281;
	public static final int GL_ATOMIC_COUNTER_BUFFER_BINDING = 0x092C1;
	public static final int GL_UNSIGNED_INT_IMAGE_CUBE = 0x09066;
	public static final int GL_IMAGE_CLASS_11_11_10 = 0x082C2;
	public static final int GL_ZERO_TO_ONE = 0x0935F;
	public static final int GL_MAX_VERTEX_STREAMS = 0x08E71;
	public static final int GL_UNSIGNED_INT_IMAGE_3D = 0x09064;
	public static final int GL_IMPLEMENTATION_COLOR_READ_FORMAT = 0x08B9B;
	public static final int GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET = 0x08E5F;
	public static final int GL_QUERY_WAIT_INVERTED = 0x08E17;
	public static final int GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS = 0x08E85;
	public static final int GL_READ_PIXELS = 0x0828C;
	public static final int GL_ALL_SHADER_BITS = 0xFFFFFF;
	public static final int GL_QUERY_BY_REGION_WAIT_INVERTED = 0x08E19;
	public static final int GL_LOCATION_COMPONENT = 0x0934A;
	public static final int GL_LOW_INT = 0x08DF3;
	public static final int GL_ARRAY_SIZE = 0x092FB;
	public static final int GL_INTERNALFORMAT_DEPTH_TYPE = 0x0827C;
	public static final int GL_MAX_SHADER_STORAGE_BLOCK_SIZE = 0x090DE;
	public static final int GL_TESS_EVALUATION_SHADER = 0x08E87;
	public static final int GL_ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS = 0x092C5;
	public static final int GL_DEBUG_SOURCE_THIRD_PARTY = 0x08249;
	public static final int GL_FRAMEBUFFER_DEFAULT_WIDTH = 0x09310;
	public static final int GL_GUILTY_CONTEXT_RESET = 0x08253;
	public static final int GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE = 0x08E24;
	public static final int GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS = 0x090D9;
	public static final int GL_DEBUG_GROUP_STACK_DEPTH = 0x0826D;
	public static final int GL_PROGRAM_OUTPUT = 0x092E4;
	public static final int GL_TESS_EVALUATION_SUBROUTINE = 0x092EA;
	public static final int GL_IMAGE_CLASS_4_X_32 = 0x082B9;
	public static final int GL_MAP_COHERENT_BIT = 0x00080;
	public static final int GL_INT_IMAGE_1D = 0x09057;
	public static final int GL_MAX_VIEWPORTS = 0x0825B;
	public static final int GL_SHADER_STORAGE_BARRIER_BIT = 0x02000;
	public static final int GL_BLOCK_INDEX = 0x092FD;
	public static final int GL_IMAGE_2D_MULTISAMPLE = 0x09055;
	public static final int GL_IMAGE_1D = 0x0904C;
	public static final int GL_MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS = 0x092CE;
	public static final int GL_COMPRESSED_SIGNED_RG11_EAC = 0x09273;
	public static final int GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS = 0x09314;
	public static final int GL_DISPATCH_INDIRECT_BUFFER_BINDING = 0x090EF;
	public static final int GL_DEBUG_TYPE_ERROR = 0x0824C;
	public static final int GL_TESS_CONTROL_SHADER = 0x08E88;
	public static final int GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS = 0x08DE8;
	public static final int GL_IMAGE_FORMAT_COMPATIBILITY_BY_SIZE = 0x090C8;
	public static final int GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH = 0x082FC;
	public static final int GL_INT_IMAGE_3D = 0x09059;
	public static final int GL_INT_IMAGE_2D = 0x09058;
	public static final int GL_MAX_NUM_COMPATIBLE_SUBROUTINES = 0x092F8;
	public static final int GL_MAX_IMAGE_SAMPLES = 0x0906D;
	public static final int GL_COMPRESSED_RGB_BPTC_SIGNED_FLOAT = 0x08E8E;
	public static final int GL_READ_PIXELS_FORMAT = 0x0828D;
	public static final int GL_SRGB_READ = 0x08297;
	public static final int GL_VIEW_CLASS_32_BITS = 0x082C8;
	public static final int GL_IMAGE_2D = 0x0904D;
	public static final int GL_VIEW_CLASS_S3TC_DXT5_RGBA = 0x082CF;
	public static final int GL_REFERENCED_BY_FRAGMENT_SHADER = 0x0930A;
	public void glBeginQueryIndexed(int target, int index, int id);
	public void glBindTransformFeedback(int target, int id);
	public void glBlendEquationi(int buf, int mode);
	public void glBlendEquationSeparatei(int buf, int modeRGB, int modeAlpha);
	public void glBlendFunci(int buf, int sfactor, int dfactor);
	public void glBlendFuncSeparatei(int buf, int srcRGB, int dstRGB, int srcAlpha, int dstAlpha);
	public void glDeleteTransformFeedbacks(int id);
	public void glDeleteTransformFeedbacks(java.nio.IntBuffer ids);
	public void glDeleteTransformFeedbacks(int n, java.nio.ByteBuffer ids);
	public void glDrawArraysIndirect(int mode, java.nio.ByteBuffer indirect);
	public void glDrawArraysIndirect(int mode, java.nio.IntBuffer indirect);
	public void glDrawArraysIndirect(int mode, long indirectOffset);
	public void glDrawElementsIndirect(int mode, int type, java.nio.ByteBuffer indirect);
	public void glDrawElementsIndirect(int mode, int type, java.nio.IntBuffer indirect);
	public void glDrawElementsIndirect(int mode, int type, long indirectOffset);
	public void glDrawTransformFeedback(int mode, int id);
	public void glDrawTransformFeedbackStream(int mode, int id, int stream);
	public void glEndQueryIndexed(int target, int index);
	public int glGenTransformFeedbacks();
	public void glGenTransformFeedbacks(java.nio.IntBuffer ids);
	public void glGenTransformFeedbacks(int n, java.nio.ByteBuffer ids);
	public java.lang.String glGetActiveSubroutineName(int program, int shadertype, int index);
	public java.lang.String glGetActiveSubroutineName(int program, int shadertype, int index, int bufsize);
	public void glGetActiveSubroutineName(int program, int shadertype, int index, java.nio.IntBuffer length, java.nio.ByteBuffer name);
	public void glGetActiveSubroutineName(int program, int shadertype, int index, int bufsize, java.nio.ByteBuffer length, java.nio.ByteBuffer name);
	public void glGetActiveSubroutineUniform(int program, int shadertype, int index, int pname, java.nio.IntBuffer values);
	public int glGetActiveSubroutineUniformi(int program, int shadertype, int index, int pname);
	public void glGetActiveSubroutineUniformi(int program, int shadertype, int index, int pname, java.nio.ByteBuffer values);
	public java.lang.String glGetActiveSubroutineUniformName(int program, int shadertype, int index);
	public java.lang.String glGetActiveSubroutineUniformName(int program, int shadertype, int index, int bufsize);
	public void glGetActiveSubroutineUniformName(int program, int shadertype, int index, java.nio.IntBuffer length, java.nio.ByteBuffer name);
	public void glGetActiveSubroutineUniformName(int program, int shadertype, int index, int bufsize, java.nio.ByteBuffer length, java.nio.ByteBuffer name);
	public void glGetProgramStage(int program, int shadertype, int pname, java.nio.IntBuffer values);
	public int glGetProgramStagei(int program, int shadertype, int pname);
	public void glGetProgramStagei(int program, int shadertype, int pname, java.nio.ByteBuffer values);
	public void glGetQueryIndexed(int target, int index, int pname, java.nio.IntBuffer params);
	public int glGetQueryIndexedi(int target, int index, int pname);
	public void glGetQueryIndexedi(int target, int index, int pname, java.nio.ByteBuffer params);
	public int glGetSubroutineIndex(int program, int shadertype, java.nio.ByteBuffer name);
	public int glGetSubroutineIndex(int program, int shadertype, java.lang.CharSequence name);
	public int glGetSubroutineUniformLocation(int program, int shadertype, java.nio.ByteBuffer name);
	public int glGetSubroutineUniformLocation(int program, int shadertype, java.lang.CharSequence name);
	public void glGetUniform(int program, int location, java.nio.DoubleBuffer params);
	public double glGetUniformd(int program, int location);
	public void glGetUniformd(int program, int location, java.nio.ByteBuffer params);
	public void glGetUniformSubroutineu(int shadertype, int location, java.nio.IntBuffer params);
	public int glGetUniformSubroutineui(int shadertype, int location);
	public void glGetUniformSubroutineui(int shadertype, int location, java.nio.ByteBuffer params);
	public boolean glIsTransformFeedback(int id);
	public void glMinSampleShading(float value);
	public void glPatchParameter(int pname, java.nio.FloatBuffer values);
	public void glPatchParameterf(int pname, java.nio.ByteBuffer values);
	public void glPatchParameteri(int pname, int value);
	public void glPauseTransformFeedback();
	public void glResumeTransformFeedback();
	public void glUniform1(int location, java.nio.DoubleBuffer value);
	public void glUniform1d(int location, double x);
	public void glUniform1d(int location, int count, java.nio.ByteBuffer value);
	public void glUniform2(int location, java.nio.DoubleBuffer value);
	public void glUniform2d(int location, double x, double y);
	public void glUniform2d(int location, int count, java.nio.ByteBuffer value);
	public void glUniform3(int location, java.nio.DoubleBuffer value);
	public void glUniform3d(int location, double x, double y, double z);
	public void glUniform3d(int location, int count, java.nio.ByteBuffer value);
	public void glUniform4(int location, java.nio.DoubleBuffer value);
	public void glUniform4d(int location, double x, double y, double z, double w);
	public void glUniform4d(int location, int count, java.nio.ByteBuffer value);
	public void glUniformMatrix2(int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glUniformMatrix2d(int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glUniformMatrix2x3(int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glUniformMatrix2x3d(int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glUniformMatrix2x4(int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glUniformMatrix2x4d(int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glUniformMatrix3(int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glUniformMatrix3d(int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glUniformMatrix3x2(int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glUniformMatrix3x2d(int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glUniformMatrix3x4(int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glUniformMatrix3x4d(int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glUniformMatrix4(int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glUniformMatrix4d(int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glUniformMatrix4x2(int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glUniformMatrix4x2d(int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glUniformMatrix4x3(int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glUniformMatrix4x3d(int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glUniformSubroutinesu(int shadertype, java.nio.IntBuffer indices);
	public void glUniformSubroutinesui(int shadertype, int index);
	public void glUniformSubroutinesui(int shadertype, int count, java.nio.ByteBuffer indices);
	public void glActiveShaderProgram(int pipeline, int program);
	public void glBindProgramPipeline(int pipeline);
	public void glClearDepthf(float depth);
	public int glCreateShaderProgram(int type, java.lang.CharSequence string);
	public int glCreateShaderProgram(int type, java.lang.CharSequence[] strings);
	public int glCreateShaderProgram(int type, int count, java.nio.ByteBuffer strings);
	public int glCreateShaderProgram(int type, PointerBuffer strings);
	public void glDeleteProgramPipelines(int pipeline);
	public void glDeleteProgramPipelines(java.nio.IntBuffer pipelines);
	public void glDeleteProgramPipelines(int n, java.nio.ByteBuffer pipelines);
	public void glDepthRangeArray(int first, java.nio.DoubleBuffer v);
	public void glDepthRangeArray(int first, int count, java.nio.ByteBuffer v);
	public void glDepthRangef(float zNear, float zFar);
	public void glDepthRangeIndexed(int index, double zNear, double zFar);
	public int glGenProgramPipelines();
	public void glGenProgramPipelines(java.nio.IntBuffer pipelines);
	public void glGenProgramPipelines(int n, java.nio.ByteBuffer pipelines);
	public double glGetDoublei(int target, int index);
	public void glGetDoublei(int target, int index, java.nio.ByteBuffer data);
	public void glGetDoublei(int target, int index, java.nio.DoubleBuffer data);
	public float glGetFloati(int target, int index);
	public void glGetFloati(int target, int index, java.nio.ByteBuffer data);
	public void glGetFloati(int target, int index, java.nio.FloatBuffer data);
	public java.nio.ByteBuffer glGetProgramBinary(int program, java.nio.IntBuffer binaryFormat);
	public void glGetProgramBinary(int program, java.nio.IntBuffer length, java.nio.IntBuffer binaryFormat, java.nio.ByteBuffer binary);
	public void glGetProgramBinary(int program, int bufSize, java.nio.ByteBuffer length, java.nio.ByteBuffer binaryFormat, java.nio.ByteBuffer binary);
	public java.nio.ByteBuffer glGetProgramBinary(int program, int bufSize, java.nio.IntBuffer binaryFormat);
	public void glGetProgramPipeline(int pipeline, int pname, java.nio.IntBuffer params);
	public int glGetProgramPipelinei(int pipeline, int pname);
	public void glGetProgramPipelinei(int pipeline, int pname, java.nio.ByteBuffer params);
	public java.lang.String glGetProgramPipelineInfoLog(int pipeline);
	public java.lang.String glGetProgramPipelineInfoLog(int pipeline, int bufSize);
	public void glGetProgramPipelineInfoLog(int pipeline, java.nio.IntBuffer length, java.nio.ByteBuffer infoLog);
	public void glGetProgramPipelineInfoLog(int pipeline, int bufSize, java.nio.ByteBuffer length, java.nio.ByteBuffer infoLog);
	public void glGetShaderPrecisionFormat(int shadertype, int precisiontype, java.nio.ByteBuffer range, java.nio.ByteBuffer precision);
	public int glGetShaderPrecisionFormat(int shadertype, int precisiontype, java.nio.IntBuffer range);
	public void glGetShaderPrecisionFormat(int shadertype, int precisiontype, java.nio.IntBuffer range, java.nio.IntBuffer precision);
	public void glGetVertexAttribL(int index, int pname, java.nio.DoubleBuffer params);
	public void glGetVertexAttribLd(int index, int pname, java.nio.ByteBuffer params);
	public boolean glIsProgramPipeline(int pipeline);
	public void glProgramBinary(int program, int binaryFormat, java.nio.ByteBuffer binary);
	public void glProgramBinary(int program, int binaryFormat, java.nio.ByteBuffer binary, int length);
	public void glProgramParameteri(int program, int pname, int value);
	public void glProgramUniform1(int program, int location, java.nio.DoubleBuffer value);
	public void glProgramUniform1(int program, int location, java.nio.FloatBuffer value);
	public void glProgramUniform1(int program, int location, java.nio.IntBuffer value);
	public void glProgramUniform1d(int program, int location, double x);
	public void glProgramUniform1d(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform1f(int program, int location, float x);
	public void glProgramUniform1f(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform1i(int program, int location, int x);
	public void glProgramUniform1i(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform1u(int program, int location, java.nio.IntBuffer value);
	public void glProgramUniform1ui(int program, int location, int x);
	public void glProgramUniform1ui(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform2(int program, int location, java.nio.DoubleBuffer value);
	public void glProgramUniform2(int program, int location, java.nio.FloatBuffer value);
	public void glProgramUniform2(int program, int location, java.nio.IntBuffer value);
	public void glProgramUniform2d(int program, int location, double x, double y);
	public void glProgramUniform2d(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform2f(int program, int location, float x, float y);
	public void glProgramUniform2f(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform2i(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform2i(int program, int location, int x, int y);
	public void glProgramUniform2u(int program, int location, java.nio.IntBuffer value);
	public void glProgramUniform2ui(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform2ui(int program, int location, int x, int y);
	public void glProgramUniform3(int program, int location, java.nio.DoubleBuffer value);
	public void glProgramUniform3(int program, int location, java.nio.FloatBuffer value);
	public void glProgramUniform3(int program, int location, java.nio.IntBuffer value);
	public void glProgramUniform3d(int program, int location, double x, double y, double z);
	public void glProgramUniform3d(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform3f(int program, int location, float x, float y, float z);
	public void glProgramUniform3f(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform3i(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform3i(int program, int location, int x, int y, int z);
	public void glProgramUniform3u(int program, int location, java.nio.IntBuffer value);
	public void glProgramUniform3ui(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform3ui(int program, int location, int x, int y, int z);
	public void glProgramUniform4(int program, int location, java.nio.DoubleBuffer value);
	public void glProgramUniform4(int program, int location, java.nio.FloatBuffer value);
	public void glProgramUniform4(int program, int location, java.nio.IntBuffer value);
	public void glProgramUniform4d(int program, int location, double x, double y, double z, double w);
	public void glProgramUniform4d(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform4f(int program, int location, float x, float y, float z, float w);
	public void glProgramUniform4f(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform4i(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform4i(int program, int location, int x, int y, int z, int w);
	public void glProgramUniform4u(int program, int location, java.nio.IntBuffer value);
	public void glProgramUniform4ui(int program, int location, int count, java.nio.ByteBuffer value);
	public void glProgramUniform4ui(int program, int location, int x, int y, int z, int w);
	public void glProgramUniformMatrix2(int program, int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glProgramUniformMatrix2(int program, int location, boolean transpose, java.nio.FloatBuffer value);
	public void glProgramUniformMatrix2d(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix2f(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix2x3(int program, int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glProgramUniformMatrix2x3(int program, int location, boolean transpose, java.nio.FloatBuffer value);
	public void glProgramUniformMatrix2x3d(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix2x3f(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix2x4(int program, int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glProgramUniformMatrix2x4(int program, int location, boolean transpose, java.nio.FloatBuffer value);
	public void glProgramUniformMatrix2x4d(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix2x4f(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix3(int program, int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glProgramUniformMatrix3(int program, int location, boolean transpose, java.nio.FloatBuffer value);
	public void glProgramUniformMatrix3d(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix3f(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix3x2(int program, int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glProgramUniformMatrix3x2(int program, int location, boolean transpose, java.nio.FloatBuffer value);
	public void glProgramUniformMatrix3x2d(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix3x2f(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix3x4(int program, int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glProgramUniformMatrix3x4(int program, int location, boolean transpose, java.nio.FloatBuffer value);
	public void glProgramUniformMatrix3x4d(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix3x4f(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix4(int program, int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glProgramUniformMatrix4(int program, int location, boolean transpose, java.nio.FloatBuffer value);
	public void glProgramUniformMatrix4d(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix4f(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix4x2(int program, int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glProgramUniformMatrix4x2(int program, int location, boolean transpose, java.nio.FloatBuffer value);
	public void glProgramUniformMatrix4x2d(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix4x2f(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix4x3(int program, int location, boolean transpose, java.nio.DoubleBuffer value);
	public void glProgramUniformMatrix4x3(int program, int location, boolean transpose, java.nio.FloatBuffer value);
	public void glProgramUniformMatrix4x3d(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glProgramUniformMatrix4x3f(int program, int location, int count, boolean transpose, java.nio.ByteBuffer value);
	public void glReleaseShaderCompiler();
	public void glScissorArray(int first, java.nio.IntBuffer v);
	public void glScissorArray(int first, int count, java.nio.ByteBuffer v);
	public void glScissorIndexed(int index, java.nio.ByteBuffer v);
	public void glScissorIndexed(int index, java.nio.IntBuffer v);
	public void glScissorIndexed(int index, int left, int bottom, int width, int height);
	public void glShaderBinary(java.nio.IntBuffer shaders, int binaryformat, java.nio.ByteBuffer binary);
	public void glShaderBinary(int count, java.nio.ByteBuffer shaders, int binaryformat, java.nio.ByteBuffer binary, int length);
	public void glUseProgramStages(int pipeline, int stages, int program);
	public void glValidateProgramPipeline(int pipeline);
	public void glVertexAttribL1(int index, java.nio.DoubleBuffer v);
	public void glVertexAttribL1d(int index, java.nio.ByteBuffer v);
	public void glVertexAttribL1d(int index, double x);
	public void glVertexAttribL2(int index, java.nio.DoubleBuffer v);
	public void glVertexAttribL2d(int index, java.nio.ByteBuffer v);
	public void glVertexAttribL2d(int index, double x, double y);
	public void glVertexAttribL3(int index, java.nio.DoubleBuffer v);
	public void glVertexAttribL3d(int index, java.nio.ByteBuffer v);
	public void glVertexAttribL3d(int index, double x, double y, double z);
	public void glVertexAttribL4(int index, java.nio.DoubleBuffer v);
	public void glVertexAttribL4d(int index, java.nio.ByteBuffer v);
	public void glVertexAttribL4d(int index, double x, double y, double z, double w);
	public void glVertexAttribLPointer(int index, int size, int stride, java.nio.DoubleBuffer pointer);
	public void glVertexAttribLPointer(int index, int size, int type, int stride, java.nio.ByteBuffer pointer);
	public void glVertexAttribLPointer(int index, int size, int type, int stride, long pointerOffset);
	public void glViewportArray(int first, java.nio.FloatBuffer v);
	public void glViewportArray(int first, int count, java.nio.ByteBuffer v);
	public void glViewportIndexed(int index, java.nio.FloatBuffer v);
	public void glViewportIndexedf(int index, java.nio.ByteBuffer v);
	public void glViewportIndexedf(int index, float x, float y, float w, float h);
	public void glBindImageTexture(int unit, int texture, int level, boolean layered, int layer, int access, int format);
	public void glDrawArraysInstancedBaseInstance(int mode, int first, int count, int primcount, int baseinstance);
	public void glDrawElementsInstancedBaseInstance(int mode, java.nio.ByteBuffer indices, int primcount, int baseinstance);
	public void glDrawElementsInstancedBaseInstance(int mode, java.nio.IntBuffer indices, int primcount, int baseinstance);
	public void glDrawElementsInstancedBaseInstance(int mode, int type, java.nio.ByteBuffer indices, int primcount, int baseinstance);
	public void glDrawElementsInstancedBaseInstance(int mode, int count, int type, java.nio.ByteBuffer indices, int primcount, int baseinstance);
	public void glDrawElementsInstancedBaseInstance(int mode, int count, int type, long indicesOffset, int primcount, int baseinstance);
	public void glDrawElementsInstancedBaseInstance(int mode, java.nio.ShortBuffer indices, int primcount, int baseinstance);
	public void glDrawElementsInstancedBaseVertexBaseInstance(int mode, java.nio.ByteBuffer indices, int primcount, int basevertex, int baseinstance);
	public void glDrawElementsInstancedBaseVertexBaseInstance(int mode, java.nio.IntBuffer indices, int primcount, int basevertex, int baseinstance);
	public void glDrawElementsInstancedBaseVertexBaseInstance(int mode, int type, java.nio.ByteBuffer indices, int primcount, int basevertex, int baseinstance);
	public void glDrawElementsInstancedBaseVertexBaseInstance(int mode, int count, int type, java.nio.ByteBuffer indices, int primcount, int basevertex, int baseinstance);
	public void glDrawElementsInstancedBaseVertexBaseInstance(int mode, int count, int type, long indicesOffset, int primcount, int basevertex, int baseinstance);
	public void glDrawElementsInstancedBaseVertexBaseInstance(int mode, java.nio.ShortBuffer indices, int primcount, int basevertex, int baseinstance);
	public void glDrawTransformFeedbackInstanced(int mode, int id, int primcount);
	public void glDrawTransformFeedbackStreamInstanced(int mode, int id, int stream, int primcount);
	public void glGetActiveAtomicCounterBuffer(int program, int bufferIndex, int pname, java.nio.IntBuffer params);
	public int glGetActiveAtomicCounterBufferi(int program, int bufferIndex, int pname);
	public void glGetActiveAtomicCounterBufferi(int program, int bufferIndex, int pname, java.nio.ByteBuffer params);
	public void glGetInternalformat(int target, int internalformat, int pname, java.nio.IntBuffer params);
	public int glGetInternalformati(int target, int internalformat, int pname);
	public void glGetInternalformati(int target, int internalformat, int pname, int bufSize, java.nio.ByteBuffer params);
	public void glMemoryBarrier(int barriers);
	public void glTexStorage1D(int target, int levels, int internalformat, int width);
	public void glTexStorage2D(int target, int levels, int internalformat, int width, int height);
	public void glTexStorage3D(int target, int levels, int internalformat, int width, int height, int depth);
	public void glBindVertexBuffer(int bindingindex, int buffer, long offset, int stride);
	public void glClearBufferData(int target, int internalformat, int format, int type, java.nio.ByteBuffer data);
	public void glClearBufferData(int target, int internalformat, int format, int type, java.nio.FloatBuffer data);
	public void glClearBufferData(int target, int internalformat, int format, int type, java.nio.IntBuffer data);
	public void glClearBufferData(int target, int internalformat, int format, int type, java.nio.ShortBuffer data);
	public void glClearBufferSubData(int target, int internalformat, long offset, long size, int format, int type, java.nio.ByteBuffer data);
	public void glClearBufferSubData(int target, int internalformat, long offset, long size, int format, int type, java.nio.FloatBuffer data);
	public void glClearBufferSubData(int target, int internalformat, long offset, long size, int format, int type, java.nio.IntBuffer data);
	public void glClearBufferSubData(int target, int internalformat, long offset, long size, int format, int type, java.nio.ShortBuffer data);
	public void glCopyImageSubData(int srcName, int srcTarget, int srcLevel, int srcX, int srcY, int srcZ, int dstName, int dstTarget, int dstLevel, int dstX, int dstY, int dstZ, int srcWidth, int srcHeight, int srcDepth);
	public void glDebugMessageCallback(DebugCallback callback);
	public void glDebugMessageCallback(long callback, long userParam);
	public void glDebugMessageControl(int source, int type, int severity, int id, boolean enabled);
	public void glDebugMessageControl(int source, int type, int severity, java.nio.IntBuffer ids, boolean enabled);
	public void glDebugMessageControl(int source, int type, int severity, int count, java.nio.ByteBuffer ids, boolean enabled);
	public void glDebugMessageInsert(int source, int type, int id, int severity, java.nio.ByteBuffer message);
	public void glDebugMessageInsert(int source, int type, int id, int severity, java.lang.CharSequence message);
	public void glDebugMessageInsert(int source, int type, int id, int severity, int length, java.nio.ByteBuffer message);
	public void glDispatchCompute(int num_groups_x, int num_groups_y, int num_groups_z);
	public void glDispatchComputeIndirect(long indirect);
	public void glFramebufferParameteri(int target, int pname, int param);
	public int glGetDebugMessageLog(int count, java.nio.IntBuffer sources, java.nio.IntBuffer types, java.nio.IntBuffer ids, java.nio.IntBuffer severities, java.nio.IntBuffer lengths, java.nio.ByteBuffer messageLog);
	public int glGetDebugMessageLog(int count, java.nio.IntBuffer sources, java.nio.IntBuffer types, java.nio.IntBuffer ids, java.nio.IntBuffer severities, java.nio.IntBuffer lengths, java.lang.CharSequence messageLog);
	public int glGetDebugMessageLog(int count, int bufsize, java.nio.ByteBuffer sources, java.nio.ByteBuffer types, java.nio.ByteBuffer ids, java.nio.ByteBuffer severities, java.nio.ByteBuffer lengths, java.nio.ByteBuffer messageLog);
	public void glGetFramebufferParameter(int target, int pname, java.nio.IntBuffer params);
	public int glGetFramebufferParameteri(int target, int pname);
	public void glGetFramebufferParameteri(int target, int pname, java.nio.ByteBuffer params);
	public void glGetInternalformat(int target, int internalformat, int pname, java.nio.LongBuffer params);
	public long glGetInternalformati64(int target, int internalformat, int pname);
	public void glGetInternalformati64(int target, int internalformat, int pname, int bufSize, java.nio.ByteBuffer params);
	public java.lang.String glGetObjectLabel(int identifier, int name);
	public java.lang.String glGetObjectLabel(int identifier, int name, int bufSize);
	public void glGetObjectLabel(int identifier, int name, java.nio.IntBuffer length, java.nio.ByteBuffer label);
	public void glGetObjectLabel(int identifier, int name, int bufSize, java.nio.ByteBuffer length, java.nio.ByteBuffer label);
	public java.lang.String glGetObjectPtrLabel(long ptr);
	public java.lang.String glGetObjectPtrLabel(long ptr, int bufSize);
	public void glGetObjectPtrLabel(long ptr, java.nio.IntBuffer length, java.nio.ByteBuffer label);
	public void glGetObjectPtrLabel(long ptr, int bufSize, java.nio.ByteBuffer length, java.nio.ByteBuffer label);
	public void glGetProgramInterface(int program, int programInterface, int pname, java.nio.IntBuffer params);
	public int glGetProgramInterfacei(int program, int programInterface, int pname);
	public void glGetProgramInterfacei(int program, int programInterface, int pname, java.nio.ByteBuffer params);
	public void glGetProgramResource(int program, int programInterface, int index, java.nio.IntBuffer props, java.nio.IntBuffer length, java.nio.IntBuffer params);
	public java.nio.IntBuffer glGetProgramResourcei(int program, int programInterface, int index, java.nio.IntBuffer props, int bufSize);
	public void glGetProgramResourcei(int program, int programInterface, int index, int propCount, java.nio.ByteBuffer props, int bufSize, java.nio.ByteBuffer length, java.nio.ByteBuffer params);
	public int glGetProgramResourceIndex(int program, int programInterface, java.nio.ByteBuffer name);
	public int glGetProgramResourceIndex(int program, int programInterface, java.lang.CharSequence name);
	public int glGetProgramResourceLocation(int program, int programInterface, java.nio.ByteBuffer name);
	public int glGetProgramResourceLocation(int program, int programInterface, java.lang.CharSequence name);
	public int glGetProgramResourceLocationIndex(int program, int programInterface, java.nio.ByteBuffer name);
	public int glGetProgramResourceLocationIndex(int program, int programInterface, java.lang.CharSequence name);
	public java.lang.String glGetProgramResourceName(int program, int programInterface, int index);
	public java.lang.String glGetProgramResourceName(int program, int programInterface, int index, int bufSize);
	public void glGetProgramResourceName(int program, int programInterface, int index, java.nio.IntBuffer length, java.nio.ByteBuffer name);
	public void glGetProgramResourceName(int program, int programInterface, int index, int bufSize, java.nio.ByteBuffer length, java.nio.ByteBuffer name);
	public void glInvalidateBufferData(int buffer);
	public void glInvalidateBufferSubData(int buffer, long offset, long length);
	public void glInvalidateFramebuffer(int target, int attachment);
	public void glInvalidateFramebuffer(int target, java.nio.IntBuffer attachments);
	public void glInvalidateFramebuffer(int target, int numAttachments, java.nio.ByteBuffer attachments);
	public void glInvalidateSubFramebuffer(int target, java.nio.IntBuffer attachments, int x, int y, int width, int height);
	public void glInvalidateSubFramebuffer(int target, int numAttachments, java.nio.ByteBuffer attachments, int x, int y, int width, int height);
	public void glInvalidateSubFramebuffer(int target, int attachment, int x, int y, int width, int height);
	public void glInvalidateTexImage(int texture, int level);
	public void glInvalidateTexSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth);
	public void glMultiDrawArraysIndirect(int mode, java.nio.ByteBuffer indirect, int primcount, int stride);
	public void glMultiDrawArraysIndirect(int mode, java.nio.IntBuffer indirect, int primcount, int stride);
	public void glMultiDrawArraysIndirect(int mode, long indirectOffset, int primcount, int stride);
	public void glMultiDrawElementsIndirect(int mode, int type, java.nio.ByteBuffer indirect, int primcount, int stride);
	public void glMultiDrawElementsIndirect(int mode, int type, java.nio.IntBuffer indirect, int primcount, int stride);
	public void glMultiDrawElementsIndirect(int mode, int type, long indirectOffset, int primcount, int stride);
	public void glObjectLabel(int identifier, int name, java.nio.ByteBuffer label);
	public void glObjectLabel(int identifier, int name, java.lang.CharSequence label);
	public void glObjectLabel(int identifier, int name, int length, java.nio.ByteBuffer label);
	public void glObjectPtrLabel(long ptr, java.nio.ByteBuffer label);
	public void glObjectPtrLabel(long ptr, java.lang.CharSequence label);
	public void glObjectPtrLabel(long ptr, int length, java.nio.ByteBuffer label);
	public void glPopDebugGroup();
	public void glPushDebugGroup(int source, int id, java.nio.ByteBuffer message);
	public void glPushDebugGroup(int source, int id, java.lang.CharSequence message);
	public void glPushDebugGroup(int source, int id, int length, java.nio.ByteBuffer message);
	public void glShaderStorageBlockBinding(int program, int storageBlockIndex, int storageBlockBinding);
	public void glTexBufferRange(int target, int internalformat, int buffer, long offset, long size);
	public void glTexStorage2DMultisample(int target, int samples, int internalformat, int width, int height, boolean fixedsamplelocations);
	public void glTexStorage3DMultisample(int target, int samples, int internalformat, int width, int height, int depth, boolean fixedsamplelocations);
	public void glTextureView(int texture, int target, int origtexture, int internalformat, int minlevel, int numlevels, int minlayer, int numlayers);
	public void glVertexAttribBinding(int attribindex, int bindingindex);
	public void glVertexAttribFormat(int attribindex, int size, int type, boolean normalized, int relativeoffset);
	public void glVertexAttribIFormat(int attribindex, int size, int type, int relativeoffset);
	public void glVertexAttribLFormat(int attribindex, int size, int type, int relativeoffset);
	public void glVertexBindingDivisor(int bindingindex, int divisor);
	public void glBindBuffersBase(int target, int first, java.nio.IntBuffer buffers);
	public void glBindBuffersBase(int target, int first, int count, java.nio.ByteBuffer buffers);
	public void glBindBuffersRange(int target, int first, java.nio.IntBuffer buffers, PointerBuffer offsets, PointerBuffer sizes);
	public void glBindBuffersRange(int target, int first, int count, java.nio.ByteBuffer buffers, java.nio.ByteBuffer offsets, java.nio.ByteBuffer sizes);
	public void glBindImageTextures(int first, java.nio.IntBuffer textures);
	public void glBindImageTextures(int first, int count, java.nio.ByteBuffer textures);
	public void glBindSamplers(int first, java.nio.IntBuffer samplers);
	public void glBindSamplers(int first, int count, java.nio.ByteBuffer samplers);
	public void glBindTextures(int first, java.nio.IntBuffer textures);
	public void glBindTextures(int first, int count, java.nio.ByteBuffer textures);
	public void glBindVertexBuffers(int first, java.nio.IntBuffer buffers, PointerBuffer offsets, java.nio.IntBuffer strides);
	public void glBindVertexBuffers(int first, int count, java.nio.ByteBuffer buffers, java.nio.ByteBuffer offsets, java.nio.ByteBuffer strides);
	public void glBufferStorage(int target, java.nio.ByteBuffer data, int flags);
	public void glBufferStorage(int target, java.nio.DoubleBuffer data, int flags);
	public void glBufferStorage(int target, java.nio.FloatBuffer data, int flags);
	public void glBufferStorage(int target, java.nio.IntBuffer data, int flags);
	public void glBufferStorage(int target, long size, java.nio.ByteBuffer data, int flags);
	public void glBufferStorage(int target, long size, int flags);
	public void glBufferStorage(int target, java.nio.ShortBuffer data, int flags);
	public void glClearTexImage(int texture, int level, int format, int type, java.nio.ByteBuffer data);
	public void glClearTexSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.ByteBuffer data);
	public void glClearTexSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.DoubleBuffer data);
	public void glClearTexSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.FloatBuffer data);
	public void glClearTexSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.IntBuffer data);
	public void glClearTexSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.ShortBuffer data);
	public void glBindTextureUnit(int unit, int texture);
	public void glBlitNamedFramebuffer(int readFramebuffer, int drawFramebuffer, int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, int mask, int filter);
	public int glCheckNamedFramebufferStatus(int framebuffer, int target);
	public void glClearNamedBufferData(int buffer, int internalformat, int format, int type, java.nio.ByteBuffer data);
	public void glClearNamedBufferData(int buffer, int internalformat, int format, int type, java.nio.FloatBuffer data);
	public void glClearNamedBufferData(int buffer, int internalformat, int format, int type, java.nio.IntBuffer data);
	public void glClearNamedBufferData(int buffer, int internalformat, int format, int type, java.nio.ShortBuffer data);
	public void glClearNamedBufferSubData(int buffer, int internalformat, long offset, long size, int format, int type, java.nio.ByteBuffer data);
	public void glClearNamedBufferSubData(int buffer, int internalformat, long offset, long size, int format, int type, java.nio.FloatBuffer data);
	public void glClearNamedBufferSubData(int buffer, int internalformat, long offset, long size, int format, int type, java.nio.IntBuffer data);
	public void glClearNamedBufferSubData(int buffer, int internalformat, long offset, long size, int format, int type, java.nio.ShortBuffer data);
	public void glClearNamedFramebuffer(int framebuffer, int buffer, int drawbuffer, java.nio.FloatBuffer value);
	public void glClearNamedFramebuffer(int framebuffer, int buffer, int drawbuffer, java.nio.IntBuffer value);
	public void glClearNamedFramebufferf(int framebuffer, int buffer, int drawbuffer, java.nio.ByteBuffer value);
	public void glClearNamedFramebufferfi(int framebuffer, int buffer, float depth, int stencil);
	public void glClearNamedFramebufferi(int framebuffer, int buffer, int drawbuffer, java.nio.ByteBuffer value);
	public void glClearNamedFramebufferu(int framebuffer, int buffer, int drawbuffer, java.nio.IntBuffer value);
	public void glClearNamedFramebufferui(int framebuffer, int buffer, int drawbuffer, java.nio.ByteBuffer value);
	public void glClipControl(int origin, int depth);
	public void glCompressedTextureSubImage1D(int texture, int level, int xoffset, int width, int format, java.nio.ByteBuffer data);
	public void glCompressedTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int imageSize, java.nio.ByteBuffer data);
	public void glCompressedTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int imageSize, long dataOffset);
	public void glCompressedTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, java.nio.ByteBuffer data);
	public void glCompressedTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int imageSize, java.nio.ByteBuffer data);
	public void glCompressedTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int imageSize, long dataOffset);
	public void glCompressedTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, java.nio.ByteBuffer data);
	public void glCompressedTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int imageSize, java.nio.ByteBuffer data);
	public void glCompressedTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int imageSize, long dataOffset);
	public void glCopyNamedBufferSubData(int readBuffer, int writeBuffer, long readOffset, long writeOffset, long size);
	public void glCopyTextureSubImage1D(int texture, int level, int xoffset, int x, int y, int width);
	public void glCopyTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int x, int y, int width, int height);
	public void glCopyTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int x, int y, int width, int height);
	public int glCreateBuffers();
	public void glCreateBuffers(java.nio.IntBuffer buffers);
	public void glCreateBuffers(int n, java.nio.ByteBuffer buffers);
	public int glCreateFramebuffers();
	public void glCreateFramebuffers(java.nio.IntBuffer framebuffers);
	public void glCreateFramebuffers(int n, java.nio.ByteBuffer framebuffers);
	public int glCreateProgramPipelines();
	public void glCreateProgramPipelines(java.nio.IntBuffer pipelines);
	public void glCreateProgramPipelines(int n, java.nio.ByteBuffer pipelines);
	public int glCreateQueries(int target);
	public void glCreateQueries(int target, java.nio.IntBuffer ids);
	public void glCreateQueries(int target, int n, java.nio.ByteBuffer ids);
	public int glCreateRenderbuffers();
	public void glCreateRenderbuffers(java.nio.IntBuffer renderbuffers);
	public void glCreateRenderbuffers(int n, java.nio.ByteBuffer renderbuffers);
	public int glCreateSamplers();
	public void glCreateSamplers(java.nio.IntBuffer samplers);
	public void glCreateSamplers(int n, java.nio.ByteBuffer samplers);
	public int glCreateTextures(int target);
	public void glCreateTextures(int target, java.nio.IntBuffer textures);
	public void glCreateTextures(int target, int n, java.nio.ByteBuffer textures);
	public int glCreateTransformFeedbacks();
	public void glCreateTransformFeedbacks(java.nio.IntBuffer ids);
	public void glCreateTransformFeedbacks(int n, java.nio.ByteBuffer ids);
	public int glCreateVertexArrays();
	public void glCreateVertexArrays(java.nio.IntBuffer arrays);
	public void glCreateVertexArrays(int n, java.nio.ByteBuffer arrays);
	public void glDisableVertexArrayAttrib(int vaobj, int index);
	public void glEnableVertexArrayAttrib(int vaobj, int index);
	public void glFlushMappedNamedBufferRange(int buffer, long offset, long length);
	public void glGenerateTextureMipmap(int texture);
	public void glGetCompressedTextureImage(int texture, int level, java.nio.ByteBuffer pixels);
	public void glGetCompressedTextureImage(int texture, int level, int bufSize, java.nio.ByteBuffer pixels);
	public void glGetCompressedTextureImage(int texture, int level, int bufSize, long pixelsOffset);
	public void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, java.nio.DoubleBuffer pixels);
	public void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, java.nio.FloatBuffer pixels);
	public void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, java.nio.IntBuffer pixels);
	public void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int bufSize, java.nio.ByteBuffer pixels);
	public void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int bufSize, long pixelsOffset);
	public void glGetCompressedTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, java.nio.ShortBuffer pixels);
	public int glGetGraphicsResetStatus();
	public void glGetNamedBufferParameter(int buffer, int pname, java.nio.IntBuffer params);
	public void glGetNamedBufferParameter(int buffer, int pname, java.nio.LongBuffer params);
	public int glGetNamedBufferParameteri(int buffer, int pname);
	public void glGetNamedBufferParameteri(int buffer, int pname, java.nio.ByteBuffer params);
	public long glGetNamedBufferParameteri64(int buffer, int pname);
	public void glGetNamedBufferParameteri64(int buffer, int pname, java.nio.ByteBuffer params);
	public long glGetNamedBufferPointer(int buffer, int pname);
	public void glGetNamedBufferPointer(int buffer, int pname, java.nio.ByteBuffer params);
	public void glGetNamedBufferPointer(int buffer, int pname, PointerBuffer params);
	public void glGetNamedBufferSubData(int buffer, long offset, java.nio.ByteBuffer data);
	public void glGetNamedBufferSubData(int buffer, long offset, java.nio.DoubleBuffer data);
	public void glGetNamedBufferSubData(int buffer, long offset, java.nio.FloatBuffer data);
	public void glGetNamedBufferSubData(int buffer, long offset, java.nio.IntBuffer data);
	public void glGetNamedBufferSubData(int buffer, long offset, long size, java.nio.ByteBuffer data);
	public void glGetNamedBufferSubData(int buffer, long offset, java.nio.ShortBuffer data);
	public void glGetNamedFramebufferAttachmentParameter(int framebuffer, int attachment, int pname, java.nio.IntBuffer params);
	public int glGetNamedFramebufferAttachmentParameteri(int framebuffer, int attachment, int pname);
	public void glGetNamedFramebufferAttachmentParameteri(int framebuffer, int attachment, int pname, java.nio.ByteBuffer params);
	public void glGetNamedFramebufferParameter(int framebuffer, int pname, java.nio.IntBuffer params);
	public int glGetNamedFramebufferParameteri(int framebuffer, int pname);
	public void glGetNamedFramebufferParameteri(int framebuffer, int pname, java.nio.ByteBuffer params);
	public void glGetNamedRenderbufferParameter(int renderbuffer, int pname, java.nio.IntBuffer params);
	public int glGetNamedRenderbufferParameteri(int renderbuffer, int pname);
	public void glGetNamedRenderbufferParameteri(int renderbuffer, int pname, java.nio.ByteBuffer params);
	public void glGetnUniform(int program, int location, java.nio.FloatBuffer params);
	public void glGetnUniformf(int program, int location, int bufSize, java.nio.ByteBuffer params);
	public void glGetnUniformi(int program, int location, java.nio.FloatBuffer params);
	public void glGetnUniformi(int program, int location, int bufSize, java.nio.ByteBuffer params);
	public void glGetnUniformui(int program, int location, java.nio.FloatBuffer params);
	public void glGetnUniformui(int program, int location, int bufSize, java.nio.ByteBuffer params);
	public void glGetTextureImage(int texture, int level, int format, int type, java.nio.DoubleBuffer pixels);
	public void glGetTextureImage(int texture, int level, int format, int type, java.nio.FloatBuffer pixels);
	public void glGetTextureImage(int texture, int level, int format, int type, java.nio.IntBuffer pixels);
	public void glGetTextureImage(int texture, int level, int format, int type, int bufSize, java.nio.ByteBuffer pixels);
	public void glGetTextureImage(int texture, int level, int format, int type, int bufSize, long pixelsOffset);
	public void glGetTextureImage(int texture, int level, int format, int type, java.nio.ShortBuffer pixels);
	public void glGetTextureLevelParameter(int texture, int level, int pname, java.nio.FloatBuffer params);
	public void glGetTextureLevelParameter(int texture, int level, int pname, java.nio.IntBuffer params);
	public float glGetTextureLevelParameterf(int texture, int level, int pname);
	public void glGetTextureLevelParameterf(int texture, int level, int pname, java.nio.ByteBuffer params);
	public int glGetTextureLevelParameteri(int texture, int level, int pname);
	public void glGetTextureLevelParameteri(int texture, int level, int pname, java.nio.ByteBuffer params);
	public void glGetTextureParameter(int texture, int pname, java.nio.FloatBuffer params);
	public void glGetTextureParameter(int texture, int pname, java.nio.IntBuffer params);
	public float glGetTextureParameterf(int texture, int pname);
	public void glGetTextureParameterf(int texture, int pname, java.nio.ByteBuffer params);
	public int glGetTextureParameteri(int texture, int pname);
	public void glGetTextureParameteri(int texture, int pname, java.nio.ByteBuffer params);
	public void glGetTextureParameterI(int texture, int pname, java.nio.IntBuffer params);
	public int glGetTextureParameterIi(int texture, int pname);
	public void glGetTextureParameterIi(int texture, int pname, java.nio.ByteBuffer params);
	public void glGetTextureParameterIu(int texture, int pname, java.nio.IntBuffer params);
	public int glGetTextureParameterIui(int texture, int pname);
	public void glGetTextureParameterIui(int texture, int pname, java.nio.ByteBuffer params);
	public void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.DoubleBuffer pixels);
	public void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.FloatBuffer pixels);
	public void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.IntBuffer pixels);
	public void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, int bufSize, java.nio.ByteBuffer pixels);
	public void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, int bufSize, long pixelsOffset);
	public void glGetTextureSubImage(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.ShortBuffer pixels);
	public void glGetTransformFeedback(int xfb, int pname, java.nio.IntBuffer param);
	public void glGetTransformFeedback(int xfb, int pname, int index, java.nio.IntBuffer param);
	public void glGetTransformFeedback(int xfb, int pname, int index, java.nio.LongBuffer param);
	public int glGetTransformFeedbacki(int xfb, int pname);
	public void glGetTransformFeedbacki(int xfb, int pname, java.nio.ByteBuffer param);
	public int glGetTransformFeedbacki(int xfb, int pname, int index);
	public void glGetTransformFeedbacki(int xfb, int pname, int index, java.nio.ByteBuffer param);
	public long glGetTransformFeedbacki64(int xfb, int pname, int index);
	public void glGetTransformFeedbacki64(int xfb, int pname, int index, java.nio.ByteBuffer param);
	public void glGetVertexArray(int vaobj, int pname, java.nio.IntBuffer param);
	public int glGetVertexArrayi(int vaobj, int pname);
	public void glGetVertexArrayi(int vaobj, int pname, java.nio.ByteBuffer param);
	public void glGetVertexArrayIndexed(int vaobj, int index, int pname, java.nio.IntBuffer param);
	public long glGetVertexArrayIndexed64i(int vaobj, int index, int pname);
	public void glGetVertexArrayIndexed64i(int vaobj, int index, int pname, java.nio.ByteBuffer param);
	public void glGetVertexArrayIndexed64i(int vaobj, int index, int pname, java.nio.LongBuffer param);
	public int glGetVertexArrayIndexedi(int vaobj, int index, int pname);
	public void glGetVertexArrayIndexedi(int vaobj, int index, int pname, java.nio.ByteBuffer param);
	public void glInvalidateNamedFramebufferData(int framebuffer, int attachment);
	public void glInvalidateNamedFramebufferData(int framebuffer, java.nio.IntBuffer attachments);
	public void glInvalidateNamedFramebufferData(int framebuffer, int numAttachments, java.nio.ByteBuffer attachments);
	public void glInvalidateNamedFramebufferSubData(int framebuffer, java.nio.IntBuffer attachments, int x, int y, int width, int height);
	public void glInvalidateNamedFramebufferSubData(int framebuffer, int numAttachments, java.nio.ByteBuffer attachments, int x, int y, int width, int height);
	public void glInvalidateNamedFramebufferSubData(int framebuffer, int attachment, int x, int y, int width, int height);
	public java.nio.ByteBuffer glMapNamedBuffer(int buffer, int access);
	public java.nio.ByteBuffer glMapNamedBuffer(int buffer, int access, java.nio.ByteBuffer old_buffer);
	public java.nio.ByteBuffer glMapNamedBuffer(int buffer, int access, int length, java.nio.ByteBuffer old_buffer);
	public java.nio.ByteBuffer glMapNamedBufferRange(int buffer, long offset, long length, int access);
	public java.nio.ByteBuffer glMapNamedBufferRange(int buffer, long offset, long length, int access, java.nio.ByteBuffer old_buffer);
	public void glMemoryBarrierByRegion(int barriers);
	public void glNamedBufferData(int buffer, java.nio.ByteBuffer data, int usage);
	public void glNamedBufferData(int buffer, java.nio.DoubleBuffer data, int usage);
	public void glNamedBufferData(int buffer, java.nio.FloatBuffer data, int usage);
	public void glNamedBufferData(int buffer, java.nio.IntBuffer data, int usage);
	public void glNamedBufferData(int buffer, long size, java.nio.ByteBuffer data, int usage);
	public void glNamedBufferData(int buffer, long size, int usage);
	public void glNamedBufferData(int buffer, java.nio.ShortBuffer data, int usage);
	public void glNamedBufferStorage(int buffer, java.nio.ByteBuffer data, int flags);
	public void glNamedBufferStorage(int buffer, java.nio.DoubleBuffer data, int flags);
	public void glNamedBufferStorage(int buffer, java.nio.FloatBuffer data, int flags);
	public void glNamedBufferStorage(int buffer, java.nio.IntBuffer data, int flags);
	public void glNamedBufferStorage(int buffer, long size, java.nio.ByteBuffer data, int flags);
	public void glNamedBufferStorage(int buffer, long size, int flags);
	public void glNamedBufferStorage(int buffer, java.nio.ShortBuffer data, int flags);
	public void glNamedBufferSubData(int buffer, long offset, java.nio.ByteBuffer data);
	public void glNamedBufferSubData(int buffer, long offset, java.nio.DoubleBuffer data);
	public void glNamedBufferSubData(int buffer, long offset, java.nio.FloatBuffer data);
	public void glNamedBufferSubData(int buffer, long offset, java.nio.IntBuffer data);
	public void glNamedBufferSubData(int buffer, long offset, long size, java.nio.ByteBuffer data);
	public void glNamedBufferSubData(int buffer, long offset, java.nio.ShortBuffer data);
	public void glNamedFramebufferDrawBuffer(int framebuffer, int buf);
	public void glNamedFramebufferDrawBuffers(int framebuffer, int buf);
	public void glNamedFramebufferDrawBuffers(int framebuffer, java.nio.IntBuffer bufs);
	public void glNamedFramebufferDrawBuffers(int framebuffer, int n, java.nio.ByteBuffer bufs);
	public void glNamedFramebufferParameteri(int framebuffer, int pname, int param);
	public void glNamedFramebufferReadBuffer(int framebuffer, int src);
	public void glNamedFramebufferRenderbuffer(int framebuffer, int attachment, int renderbuffertarget, int renderbuffer);
	public void glNamedFramebufferTexture(int framebuffer, int attachment, int texture, int level);
	public void glNamedFramebufferTextureLayer(int framebuffer, int attachment, int texture, int level, int layer);
	public void glNamedRenderbufferStorage(int renderbuffer, int internalformat, int width, int height);
	public void glNamedRenderbufferStorageMultisample(int renderbuffer, int samples, int internalformat, int width, int height);
	public void glReadnPixels(int x, int y, int width, int height, int format, int type, java.nio.FloatBuffer pixels);
	public void glReadnPixels(int x, int y, int width, int height, int format, int type, java.nio.IntBuffer pixels);
	public void glReadnPixels(int x, int y, int width, int height, int format, int type, int bufSize, java.nio.ByteBuffer pixels);
	public void glReadnPixels(int x, int y, int width, int height, int format, int type, int bufSize, long pixelsOffset);
	public void glReadnPixels(int x, int y, int width, int height, int format, int type, java.nio.ShortBuffer pixels);
	public void glTextureBarrier();
	public void glTextureBuffer(int texture, int internalformat, int buffer);
	public void glTextureBufferRange(int texture, int internalformat, int buffer, long offset, long size);
	public void glTextureParameter(int texture, int pname, java.nio.FloatBuffer params);
	public void glTextureParameter(int texture, int pname, java.nio.IntBuffer params);
	public void glTextureParameterf(int texture, int pname, java.nio.ByteBuffer params);
	public void glTextureParameterf(int texture, int pname, float param);
	public void glTextureParameteri(int texture, int pname, java.nio.ByteBuffer params);
	public void glTextureParameteri(int texture, int pname, int param);
	public void glTextureParameterI(int texture, int pname, java.nio.IntBuffer params);
	public void glTextureParameterIi(int texture, int pname, java.nio.ByteBuffer params);
	public void glTextureParameterIi(int texture, int pname, int param);
	public void glTextureParameterIu(int texture, int pname, java.nio.IntBuffer params);
	public void glTextureParameterIui(int texture, int pname, java.nio.ByteBuffer params);
	public void glTextureParameterIui(int texture, int pname, int param);
	public void glTextureStorage1D(int texture, int levels, int internalformat, int width);
	public void glTextureStorage2D(int texture, int levels, int internalformat, int width, int height);
	public void glTextureStorage2DMultisample(int texture, int samples, int internalformat, int width, int height, boolean fixedsamplelocations);
	public void glTextureStorage3D(int texture, int levels, int internalformat, int width, int height, int depth);
	public void glTextureStorage3DMultisample(int texture, int samples, int internalformat, int width, int height, int depth, boolean fixedsamplelocations);
	public void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, java.nio.ByteBuffer pixels);
	public void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, java.nio.DoubleBuffer pixels);
	public void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, java.nio.FloatBuffer pixels);
	public void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, java.nio.IntBuffer pixels);
	public void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, long pixelsOffset);
	public void glTextureSubImage1D(int texture, int level, int xoffset, int width, int format, int type, java.nio.ShortBuffer pixels);
	public void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, java.nio.ByteBuffer pixels);
	public void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, java.nio.DoubleBuffer pixels);
	public void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, java.nio.FloatBuffer pixels);
	public void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, java.nio.IntBuffer pixels);
	public void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, long pixelsOffset);
	public void glTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int width, int height, int format, int type, java.nio.ShortBuffer pixels);
	public void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.ByteBuffer pixels);
	public void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.DoubleBuffer pixels);
	public void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.FloatBuffer pixels);
	public void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.IntBuffer pixels);
	public void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, long pixelsOffset);
	public void glTextureSubImage3D(int texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth, int format, int type, java.nio.ShortBuffer pixels);
	public void glTransformFeedbackBufferBase(int xfb, int index, int buffer);
	public void glTransformFeedbackBufferRange(int xfb, int index, int buffer, long offset, long size);
	public boolean glUnmapNamedBuffer(int buffer);
	public void glVertexArrayAttribBinding(int vaobj, int attribindex, int bindingindex);
	public void glVertexArrayAttribFormat(int vaobj, int attribindex, int size, int type, boolean normalized, int relativeoffset);
	public void glVertexArrayAttribIFormat(int vaobj, int attribindex, int size, int type, int relativeoffset);
	public void glVertexArrayAttribLFormat(int vaobj, int attribindex, int size, int type, int relativeoffset);
	public void glVertexArrayBindingDivisor(int vaobj, int bindingindex, int divisor);
	public void glVertexArrayElementBuffer(int vaobj, int buffer);
	public void glVertexArrayVertexBuffer(int vaobj, int bindingindex, int buffer, long offset, int stride);
	public void glVertexArrayVertexBuffers(int vaobj, int first, java.nio.IntBuffer buffers, PointerBuffer offsets, java.nio.IntBuffer strides);
	public void glVertexArrayVertexBuffers(int vaobj, int first, int count, java.nio.ByteBuffer buffers, java.nio.ByteBuffer offsets, java.nio.ByteBuffer strides);
	public GL getContext();
}
